<?php
// $Id$

/**
 * Implementation of hook_install().
 */
function alinks_install() {
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':
      db_query("CREATE TABLE {alinks} (
        id int(10) unsigned NOT NULL auto_increment,
        alink_text varchar(255) NOT NULL default '',
        alink_url varchar(255) NOT NULL default '',
        url_title varchar(255) NOT NULL default '',
        PRIMARY KEY  (id)
      ) /*!40100 DEFAULT CHARACTER SET UTF8 */ ");
  }
}
