<?php
/**
 * @file
 * this module allows users to associates defined text to links
 */

/**
 * Implementation of hook_permission().
 */
function alinks_permission() {

  return array(
    'administer alinks' => array(
      'title' => t('administer alinks'),
    ),
    'edit alinks' => array(
      'title' => t('edit alinks'),
    ),
  );
}

/**
 * Theme function for the list of alinks
 */
function alinks_theme() {

  return array('alinks_list' => array(
      'render element' => 'form',
    )
  );
}

/**
 * @FIXME
 * This implementation of hook_menu() cannot be automatically converted because
 * it contains logic (i.e., branching statements, function calls, object
 * instantiation, etc.) You will need to convert it manually. Sorry!
 *
 * For more information on how to convert hook_menu() to Drupal 8's new routing
 * and linking systems, see https://api.drupal.org/api/drupal/core%21includes%21menu.inc/group/menu/8
 */

/*
function alinks_menu() {
  $items = array();
  $admin = array('administer site configuration');
  $editor = array('edit alinks');

  $items['admin/config/content/alinks'] = array(
    'title' => t('Alinks'),
    'description' => t('Set the preferences for Alinks module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alinks_admin_settings'),
    'access arguments' => $admin,
  );
  $items['admin/structure/alinks'] = array(
    'title' => t('Alinks'),
    'description' => t('Define & edit alinks'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alinks_add_form'),
    'access arguments' => $editor,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/alinks/add'] = array(
    'title' => t('Add Alink'),
    'description' => t('Add alink'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alinks_add_form'),
    'access arguments' => $editor,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/structure/alinks/edit'] = array(
    'title' => t('Edit Alinks'),
    'description' => t('Edit alinks'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alinks_edit_form'),
    'access arguments' => $editor,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}
*/
/**
 * Generate the page that will render the forms for adding and editing Alinks
 */
function alinks_page() {
  $output = \Drupal::formBuilder()->getForm('alinks_add_form');
  $output .= \Drupal::formBuilder()->getForm('alinks_edit_form');

  return $output;
}

/**
 * Implementation of hook_node_view().
 */
function alinks_node_view(array &$build, \Drupal\node\NodeInterface $node, $view_mode, $langcode) {
  $node_types = \Drupal::config('alinks.settings')->get('node_types');
  if (!is_array($node_types)) {
    return;
  }

  $node_types = in_array($node->getType(), $node_types, TRUE);
  if ($node_types) {
    $words = alinks_get_strings();
    if ($words) {
      if (is_array($words) && !empty($words) && isset($node->content['body'][0]['#markup'])) {
        $node->content['body'][0]['#markup'] = alinks_make_links($node->content['body'][0]['#markup'], $words);
      }
    }
  }
}

/**
 * Get the strings we have to replace from the database
 */
function alinks_get_strings() {
  $alink = array();
  $result = db_query("SELECT * FROM {alinks} ORDER BY alink_weight");


  if ($result->rowCount() > 0) {
    foreach ($result as $alinks) {
      $alink[$alinks->id] = $alinks;
    }
  }

  return $alink;
}

/**
 * Transform the first instance of any word defined to links
 */
function alinks_make_links($body, $words) {
  if (is_array($words) && isset($body)) {

    // create the replacement array
    $url = (drupal_lookup_path('alias', $_GET['q'])) ? drupal_lookup_path('alias', $_GET['q']) : $_GET['q'];
    $i = 0;
    $title = 'alink_replaced\1alink_replaced';
    $alink_options = array();
    $links_chars = array('/', '-');
    $links_chars_replace = array('alink_slash', 'alink_minus');
    $replacement = array();

    foreach ($words as $word) {
      if ($word->alink_url != $url) {
        $alink_start_boundary = ($word->alink_start_boundary == 1) ? 'B' : 'b';
        $alink_end_boundary = ($word->alink_end_boundary == 1) ? 'B' : 'b';
        $alink_case_insensivity = ($word->alink_case_insensitive == 1) ? 'i' : '';
        $word->alink_text = trim(htmlspecialchars($word->alink_text));

        $alink_text[] = '$\\' . $alink_start_boundary . '(' . preg_quote($word->alink_text, '$') . ')\\' . $alink_end_boundary . '(?!((?!alink_replaced).)*alink_replaced</a>)$u' . $alink_case_insensivity;

        if ($word->alink_external != 1) {
          $alink_path = 'alink_check' . str_replace('/', 'alink_slash', $word->alink_url) . 'alink_check';
        }
        else {
          $alink_path = str_replace($links_chars, $links_chars_replace, $word->alink_url) . 'alink_check';
          $alink_options['absolute'] =  TRUE;
        }
        if (!empty($word->alink_class)) {
          $alink_class = 'alink_check' . str_replace(' ', 'alink_space', $word->alink_class) . 'alink_check';
          $alink_options['attributes']['class'] = $alink_class;
        }
        if (!empty($word->url_title)) {
          $alink_title = 'alink_check' . str_replace(' ', 'alink_space', \Drupal\Component\Utility\SafeMarkup::checkPlain($word->url_title)) . 'alink_check';
          $alink_options['attributes']['title'] = $alink_title;
        }
        $alink_url[] = new Link($title, $alink_path, $alink_options);
        $i++;
      }
    }
    if ($i > 0) {
      $alink_url = str_replace(array('&amp;amp;', '&amp;lt;', '&amp;gt;'), array('&amp;', '&lt;', '&gt;'), $alink_url);

      // we replace new lines with a temporary delimiter
      $carriage  = array("\r\n", "\n", "\r");
      $carriage_replacement = array(" cariage_replacement_rn ", " cariage_replacement_n ", " cariage_replacement_r ");
      $body = str_replace($carriage, $carriage_replacement, $body);

      // we get out the already existing links
      preg_match_all('/\<a\s.*?\>(.*?)\<\/a\>/i', $body, $linka);

      // create the replacement array
      foreach ($linka[0] as $key => $values) {
        $replacement[] = ' alink_delimiter_' . $key . ' ';
      }

      // replace the links with the replacement text
      $body = str_replace($linka[0], $replacement, $body);

      // we get all the text that is not inside a html tag from the modified text
      preg_match_all('/\>(.*?)\</', $body, $output);
      $output[0] = array_unique($output[0]);
      $output[1] = array_unique($output[1]);

      // transform the result array to a string so we can use the limit argument
      $text = implode(' alink_delimiter_one_string ', $output[1]);
      $limit = \Drupal::config('alinks.settings')->get('alinks_limit');

      // make the actual replacement
      if ($limit == -1) {
        $output[1] = preg_replace($alink_text, $alink_url, $text);
      }
      else {
        $output[1] = preg_replace($alink_text, $alink_url, $text, $limit);
      }

      // rebuild the array
      $output[1] = explode(' alink_delimiter_one_string ', $output[1]);
      $our_output = array();
      $i = 0;

      // we make sure the text will pe replaced outside any tag
      foreach ($output[1] as $key => $values) {
        if (!$values) {
          $our_output[$i] = '><';
        }
        else {
          $our_output[$i] = str_replace($values, '>' . $values . '<', $values);
        }
        $i++;
      }

      // insert the new text in the full text
      $body = str_replace($output[0], $our_output, $body);

      // and put back the links in the text
      $body = str_replace($replacement, $linka[0], $body);
      $body = str_replace('alink_check', '', $body);
      $body = str_replace('alink_replaced', '', $body);
      $body = str_replace('alink_space', ' ', $body);
      $body = str_replace($links_chars_replace, $links_chars, $body);

      // and finaly put back the new lines
      $body = str_replace($carriage_replacement, $carriage, $body);
    }
  }

  return $body;
}

/**
 * Generate the form used to add alinks to drupal
 */
function alinks_add_form() {

  $form['alinks_add_form'] = array(
    '#type' => 'fieldset',
    '#title' => t('Add alink'),
    '#description' => t('Use this form to add alinks'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['alinks_add_form']['start_boundary'] = array(
    '#type' => 'checkbox',
    '#title' => t('Start Boundary'),
    '#description' => t('Enable if the string doesn\'t begin with an alphanumeric or underscore character.'),
  );
  $form['alinks_add_form']['word'] = array(
    '#type' => 'textfield',
    '#title' => t('Word/Phrase'),
    '#size' => 30,
    '#maxlength' => 255,
    '#description' => t('The word or phrase you wish to convert to a link. This field is case sensitive.'),
    '#required' => TRUE
  );
  $form['alinks_add_form']['end_boundary'] = array(
    '#type' => 'checkbox',
    '#title' => t('End Boundary'),
    '#description' => t('Enable if the string doesn\'t end with an alphanumeric or underscore character.'),
  );
  $form['alinks_add_form']['case_insensitive'] = array(
    '#type' => 'checkbox',
    '#title' => t('Case Insensitivity'),
    '#description' => t('By default alinks are CaSe SeNsItIvE. Chech this checkbox if you want this particular ' .
                        'alink to be case insensitive.'),
  );
  $form['alinks_add_form']['url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL'),
    '#size' => 30,
    '#maxlength' => 255,
    '#description' => t('The URL of the page to link to. Internal (Drupal) links take the form "my/page", from the ' .
                        'full URL of "example.com/my/page".'),
    '#required' => TRUE
  );
  $form['alinks_add_form']['url_title'] = array(
    '#type' => 'textfield',
    '#title' => t('URL Title'),
    '#size' => 30,
    '#maxlength' => 255,
    '#description' => t('Title for the above URL. It will be embedded in the created link and appear as a tooltip ' .
                        'when hovering the mouse over the link.')
  );
  $form['alinks_add_form']['external'] = array(
    '#type' => 'checkbox',
    '#title' => t('External Link'),
    '#description' => t('Check this if the link is to an external domain and be sure to include http:// in the link.'),
  );
  $form['alinks_add_form']['class'] = array(
    '#type' => 'textfield',
    '#title' => t('Class'),
    '#size' => 30,
    '#maxlength' => 255,
    '#default_value' => 'alinks-link',
    '#description' => t('Use this to add a class for the link. Default value is "alinks-link".'),
  );
  $form['alinks_add_form']['weight'] = array(
    '#type' => 'weight',
    '#title' => t('Weight'),
  );
  $form['alinks_add_form']['save'] = array(
    '#type' => 'submit',
    '#value' => t('Add alink'),
  );

  return $form;
}
