alinks.alink.*:
  type: config_entity
  label: 'Alink config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    start_boundary:
        type: integer
        label: 'Start Boundary'
    text:
      type: string
      label: 'Text'
    end_boundary:
      type: integer
      label: 'End Boundary'
    case_insensitive:
      type: string
      label: 'Case Insensitive'
    url:
      type: string
      label: 'URL'
    url_title:
      type: string
      label: 'URL Title'
    external:
      type: integer
      label: 'External'
    class:
      type: string
      label: 'Text'
    weight:
      type: integer
      label: 'Weight'
